variables:
 GIT_STRATEGY: none

stages:
 - build
 - test
 - doc

west_build:
 tags: [rcc,docker,node-01]
 stage: build
 image: ubuntu:latest
 before_script:
   - apt-get update > /dev/null
   - apt-get install -qq git > /dev/null 
   - apt-get install -qq build-essential gfortran wget python-pip python-dev > /dev/null
   - apt-get install -qq libopenmpi-dev openmpi-bin > /dev/null
   - apt-get install -qq libblas-dev liblapack-dev fftw3 fftw3-dev pkg-config > /dev/null
 script:
   - git clone -b 'qe-6.1.0' --single-branch --depth 1 https://gitlab.com/QEF/q-e.git QEDIR
   - cd QEDIR
   - git describe
   - ./configure
   - make -j pw
   - ls bin
   - git clone -b $CI_COMMIT_REF_NAME $CI_REPOSITORY_URL West
   - cd West
   - git describe
   - make
   - ls ../bin 

west_build_intel:
 tags: [rcc,docker,node-01]
 stage: build
 image: centos:centos7
 before_script:
   - yum -y update > /dev/null
   - yum -y install yum-utils > /dev/null
   - yum -y install centos-release-scl-rh > /dev/null
   - yum -y install devtoolset-3 > /dev/null
   - yum -y install vim > /dev/null 
   - yum -y install wget pkgconfig git make > /dev/null
   - export TZ="US/Central"
   - rm -f /etc/localtime
   - cp  /usr/share/zoneinfo/$TZ  /etc/localtime
 script:
   - echo "JHSKONE"
   - echo "$PATH"
   - echo "$LD_LIBRARY_PATH"
   - git clone -b 'qe-6.1.0' --single-branch --depth 1 https://gitlab.com/QEF/q-e.git QEDIR
   - cd QEDIR
   - git describe
   - export PATH=/opt/intel/impi/5.1.3.210/bin:/opt/intel/2016up3/bin:$PATH
   - export LD_LIBRARY_PATH=/opt/intel/impi/5.1.3.210/lib:/opt/intel/mkl/lib/intel64:/opt/intel/2016up3/lib/intel64:/opt/intel/2016up3/ipp/lib/intel64:$LD_LIBRARY_PATH
   - export F77=mpiifort
   - export CC=icc
   - export LD=mpiifort
   - export MPIF90=mpiifort
   - export FC=ifort
   - export I_MPI_F90=ifort
   - which ifort
   - which mpiifort 
   - ./configure 
   - sleep 700s
   - make -j pw
   - ls bin
   - git clone -b $CI_COMMIT_REF_NAME $CI_REPOSITORY_URL West
   - cd West
   - git describe
   - make
   - ls ../bin 

west_test_gamma:
 tags: [rcc,docker,node-01]
 stage: test
 image: ubuntu:latest
 before_script:
   - apt-get update > /dev/null
   - apt-get install -qq git > /dev/null 
   - apt-get install -qq build-essential gfortran wget python-pip python-dev > /dev/null
   - apt-get install -qq libopenmpi-dev openmpi-bin > /dev/null
   - apt-get install -qq libblas-dev liblapack-dev fftw3 fftw3-dev pkg-config > /dev/null
 script:
   - git clone -b 'qe-6.1.0' --single-branch --depth 1 https://gitlab.com/QEF/q-e.git QEDIR
   - cd QEDIR
   - ./configure FFLAGS="-ffpe-summary=none" > /dev/null
   - make -j pw > /dev/null
   - git clone -b $CI_COMMIT_REF_NAME $CI_REPOSITORY_URL West
   - cd West 
   - make > /dev/null
   - cd test-suite 
   - make NP=28 NI=1 NT=1 

west_doc_build:
 tags: [rcc,docker,node-01]
 stage: doc
 image: continuumio/miniconda3:latest
 before_script:
   - apt-get update > /dev/null
   - export TZ="US/Central"
   - apt-get install -qq make > /dev/null
   - apt-get install -qq pandoc > /dev/null
   - rm -f /etc/localtime
   - cp  /usr/share/zoneinfo/$TZ  /etc/localtime
   - pip install -q --upgrade pip
   - pip install -q nbsphinx
   - pip install -q sphinx_rtd_theme
   - pip install -q ipython
 script:
   - git clone -b $CI_COMMIT_REF_NAME $CI_REPOSITORY_URL West
   - cd West
   - git describe
   - cd doc
   - make html
   - ls _build/html
