variables:
  GIT_STRATEGY: none
  QE_VERSION: qe-6.1.0

stages:
  - build
  - test
  - doc

.template_bot_start:
  tags: [rcc,docker,node-01]
  image: miccomcenter/bot:$CI_JOB_NAME
  before_script:
    - if [ -z $GCC_VERSION ]; then echo "not set"; else echo $GCC_VERSION; fi
    - if [ -z $LAPACK_VERSION ]; then echo "not set"; else echo $LAPACK_VERSION; fi
    - if [ -z $XERCES_VERSION ]; then echo "not set"; else echo $XERCES_VERSION; fi
    - if [ -z $OPENMPI_VERSION ]; then echo "not set"; else echo $OPENMPI_VERSION; fi
    - if [ -z $MPICH_VERSION ]; then echo "not set"; else echo $MPICH_VERSION; fi
    - if [ -z $SCALAPACK_VERSION ]; then echo "not set"; else echo $SCALAPACK_VERSION; fi
    - if [ -z $FFTW_VERSION ]; then echo "not set"; else echo $FFTW_VERSION; fi
    - if [ -z $PYTHON_VERSION ]; then echo "not set"; else echo $PYTHON_VERSION; fi
    - if [ -z $PYTHON_PIP_VERSION ]; then echo "not set"; else echo $PYTHON_PIP_VERSION; fi

.template_build:
  stage: build
  script:
    - git clone -b $QE_VERSION --single-branch --depth 1 https://gitlab.com/QEF/q-e.git QEDIR
    - cd QEDIR
    - git describe --tags --always
    - ./configure
    - make -j8 pw
    - ls bin
    - git clone -b $CI_COMMIT_REF_NAME $CI_REPOSITORY_URL West
    - cd West
    - git describe --tags --always
    - make conf PYT=python3 PYT_LDFLAGS="`python3-config --ldflags --embed`"
    - make all
    - ls ../bin

.template_test:
  stage: test
  script:
    - git clone -b $QE_VERSION --single-branch --depth 1 https://gitlab.com/QEF/q-e.git QEDIR
    - cd QEDIR
    - git describe --tags --always
    - ./configure
    - make -j8 pw
    - ls bin
    - git clone -b $CI_COMMIT_REF_NAME $CI_REPOSITORY_URL West
    - cd West
    - git describe --tags --always
    - make conf PYT=python3 PYT_LDFLAGS="`python3-config --ldflags --embed`"
    - make all
    - cd test-suite
    - make NP=8 NI=1 NT=1
  artifacts:
    when: on_failure
    paths:
      - QEDIR/West/test-suite/test*/*.out
      - QEDIR/West/test-suite/test*/*.err
      - QEDIR/West/test-suite/test*/*.tab
      - QEDIR/West/test-suite/test*/test*/*.xml
      - QEDIR/West/test-suite/test*/test*/*.json
    expire_in: 3 days

gcc840:
  extends:
    - .template_bot_start
    - .template_build

gcc930:
  extends:
    - .template_bot_start
    - .template_build

gcc840_t:
  extends:
    - .template_bot_start
    - .template_test
  image: miccomcenter/bot:gcc840

gcc930_t:
  extends:
    - .template_bot_start
    - .template_test
  image: miccomcenter/bot:gcc930

west_doc_build:
  tags: [rcc,docker,node-01]
  stage: doc
  image: continuumio/miniconda3:latest
  before_script:
    - apt-get update > /dev/null
    - export TZ="US/Central"
    - apt-get install -qq make > /dev/null
    - apt-get install -qq pandoc > /dev/null
    - rm -f /etc/localtime
    - cp /usr/share/zoneinfo/$TZ /etc/localtime
    - pip install -q --upgrade pip
    - pip install -q nbsphinx
    - pip install -q sphinx_rtd_theme
    - pip install -q ipython
  script:
    - git clone -b $CI_COMMIT_REF_NAME $CI_REPOSITORY_URL West
    - cd West
    - git describe --tags --always
    - cd Doc
    - make html
    - ls _build/html
