name: Doc

on: [push, pull_request]

jobs:
  doc:
    runs-on: ubuntu-latest
    container: continuumio/miniconda3:latest

    steps:
    - uses: actions/checkout@v3
    - name: Init
      run: |
        apt-get update
        apt-get install -qq make
        apt-get install -qq pandoc
        pip install -q -U pip
        pip install -q -U nbsphinx
        pip install -q -U sphinx_rtd_theme
        pip install -q -U ipython
        pip install -q -U ipykernel
    - name: Doc
      run: |
        cd Doc
        make html
